# Generated by Django 3.1.4 on 2020-12-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='movie metascore'),
        ),
    ]
