# Generated by Django 3.1.4 on 2020-12-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201214_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['name'], 'verbose_name_plural': 'contributors'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id'], 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='movieactor',
            options={'ordering': ['movie__id', 'position'], 'verbose_name_plural': 'movieactors'},
        ),
        migrations.AlterModelOptions(
            name='moviedirector',
            options={'ordering': ['movie__id', 'position'], 'verbose_name_plural': 'moviedirectors'},
        ),
        migrations.AlterModelOptions(
            name='moviewriter',
            options={'ordering': ['movie__id', 'position'], 'verbose_name_plural': 'moviewriters'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['name'], 'verbose_name_plural': 'ratings'},
        ),
    ]
